2-data-pickling-template
Pawelooo/My-CRM pull request #10
Opened 2023-05-25 17:14 UTC by Pawelooo

2023-05-25 17:19 UTC, JaRutkowski requested changes
Please see the comments.

2023-05-25 17:19 UTC, JaRutkowski commented on controller.py
> +        self.model.get_from_file()
Could u please print the results taken from the file and save the data provided to `save_to_file()` method?
The user should be able to save the `Test` object and retrieve the data from the file as the list of `Test` objects.

2023-05-25 17:19 UTC, JaRutkowski commented on model.py
>          self.test = ""
What is the purpose of the test field?

2023-05-25 19:05 UTC, Pawelooo reviewed
This code

2023-06-01 18:04 UTC, JaRutkowski requested changes

2023-06-01 18:04 UTC, JaRutkowski commented on src/view/view.py
>      def get_attribute(self):
I recommend making the `View` more generic, let's not focus on printing something specific, instead of that please print just a str message, passed as a parameter. In terms of getting data from the console, please let the user decide, what kind of message should be printed.

2023-06-01 18:04 UTC, JaRutkowski commented on src/model/model.py
> +from src.model.test import Test
Is the `src.model.test` used here?

2023-06-01 18:04 UTC, JaRutkowski commented on src/main.py
> +import pickle
Is it used here?

2023-06-01 18:04 UTC, JaRutkowski requested changes
Please see the comments.

2023-06-01 18:14 UTC, JaRutkowski approved these changes

2023-06-01 18:15 UTC, merged