#37 question random modes
Pawelooo/My-CRM pull request #41
Opened 2023-08-05 11:10 UTC by Pawelooo

2023-08-06 16:45 UTC, JaRutkowski requested changes

2023-08-06 16:45 UTC, JaRutkowski commented on src/service/question_service.py
> +        question_not_used = [question for question in questions if
Could u please try to use  the Set data structure for this?

2023-08-06 16:48 UTC, Pawelooo commented on src/service/question_service.py
> +        question_not_used = [question for question in questions if
Ofcourse

2023-08-08 18:36 UTC, JaRutkowski approved these changes

2023-08-08 18:36 UTC, JaRutkowski commented on src/service/question_service.py
> +
Please remove, and take care of such kind additional spaces/new lines etc. It's reducing the code quality.

2023-08-08 18:40 UTC, merged